"""001_initial_database_schema

Revision ID: 947c26fdf063
Revises: None
Create Date: 2026-09-23 07:03:20.375592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '947c26fdf063'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('current_risk_level', sa.String(length=20), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_user_id'), ['user_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'sequence_number', name='uq_messages_conversation_sequence')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)

    op.create_table('ai_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('user_message_id', sa.UUID(), nullable=True),
    sa.Column('ai_message_id', sa.UUID(), nullable=True),
    sa.Column('response_source', sa.String(length=50), nullable=False),
    sa.Column('response_type', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('response_content', sa.Text(), nullable=False),
    sa.Column('cbt_data', sa.JSON(), nullable=True),
    sa.Column('llm_metadata', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ai_message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_responses_ai_message_id'), ['ai_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_responses_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_responses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_responses_response_source'), ['response_source'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_responses_response_type'), ['response_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_responses_user_message_id'), ['user_message_id'], unique=False)

    op.create_table('message_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('safety_risk_level', sa.String(length=20), nullable=False),
    sa.Column('needs_safety_alert', sa.Boolean(), nullable=False),
    sa.Column('safety_probabilities', sa.JSON(), nullable=False),
    sa.Column('distortion_class', sa.String(length=50), nullable=False),
    sa.Column('distortion_confidence', sa.Float(), nullable=False),
    sa.Column('distortion_probabilities', sa.JSON(), nullable=False),
    sa.Column('entities', sa.JSON(), nullable=False),
    sa.Column('model_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_analyses_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_analyses_distortion_class'), ['distortion_class'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_analyses_message_id'), ['message_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_message_analyses_safety_risk_level'), ['safety_risk_level'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_analyses_safety_risk_level'))
        batch_op.drop_index(batch_op.f('ix_message_analyses_message_id'))
        batch_op.drop_index(batch_op.f('ix_message_analyses_distortion_class'))
        batch_op.drop_index(batch_op.f('ix_message_analyses_conversation_id'))

    op.drop_table('message_analyses')
    with op.batch_alter_table('ai_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_responses_user_message_id'))
        batch_op.drop_index(batch_op.f('ix_ai_responses_response_type'))
        batch_op.drop_index(batch_op.f('ix_ai_responses_response_source'))
        batch_op.drop_index(batch_op.f('ix_ai_responses_created_at'))
        batch_op.drop_index(batch_op.f('ix_ai_responses_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_ai_responses_ai_message_id'))

    op.drop_table('ai_responses')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    op.drop_table('messages')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_user_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_created_at'))

    op.drop_table('conversations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
